---
title: "Blocks in HTML"
format: html
number-sections: true
warning: false
---

## R Code chunk

`{/R Code Chunk}`

```{r}
# normal executable
qnorm(0.95)
```

```{r}
#| eval: FALSE
 #| eval: false
qnorm(0.95)
```

(No output)

------------------------------------------------------------------------

## Display - Code block

`{ / Code Block... <source code display> }`

### Display `R`

``` {.r style="border: 1px solid"}
# style="border:black 1px solid"

qnorm(0.95)
```

### Display `latex`

``` {.latex style="border: 1px solid;"}
\begin{align}
  \bar x = \frac{\sum x_i}{n} \\
  \sigma^2
\end{align}
```

### Display data `default`

``` {.default style="border: black 1px solid; background: white"}
{border: black 1px solid; background: white}

Source: Example 8.17 Devore
Data: vector of measurements

22.7 16.3 13.6 16.8 29.9 15.9 14.0 15.0 14.1 18.1 22.8 27.6 
16.4 16.1 19.0 13.5 18.9 20.2 19.7 18.2 15.4 15.7 19.0 11.5 
18.4 16.0 16.9 12.0 40.1 19.2
```

------------------------------------------------------------------------

## Div Block

`{/ Div... } can format with css html`

### Div block - embed TeX

::: {style="border: 1px solid black;"}
$$
\int udv = uv - \int vdu
$$
:::

### Div Block - css and padding

::: {#Theorem .theorem style="border: 1px solid black; background-color: gainsboro; padding:20px"}
$\textbf{Gosset's Theorem}$

If $X_1, X_2, \ldots, X_n$ is a random sample from a $N(\mu, \sigma)$ distribution, then the rv

$$
 \frac{\bar X - \mu}{S/\sqrt{n}}
$$

has the t distribution with (n-1) degrees of freedom, $t_{n-1}.$
:::
